-- MySQL Script generated by MySQL Workbench
-- 04/24/15 11:49:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cantina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cantina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cantina` DEFAULT CHARACTER SET utf8 ;
USE `cantina` ;

-- -----------------------------------------------------
-- Table `cantina`.`completedorders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`completedorders` (
  `OrderID` INT(11) NOT NULL DEFAULT '0',
  `CustomerName` VARCHAR(255) NULL DEFAULT NULL,
  `FirstItem` VARCHAR(255) NULL DEFAULT NULL,
  `SecondItem` VARCHAR(255) NULL DEFAULT NULL,
  `ThirdItem` VARCHAR(255) NULL DEFAULT NULL,
  `FourthItem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `CustomerName` (`CustomerName` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cantina`.`orderqueue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`orderqueue` (
  `OrderID` INT(11) NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(255) NULL DEFAULT NULL,
  `FirstItem` VARCHAR(255) NULL DEFAULT NULL,
  `SecondItem` VARCHAR(255) NULL DEFAULT NULL,
  `ThirdItem` VARCHAR(255) NULL DEFAULT NULL,
  `FourthItem` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `CustomerName` (`CustomerName` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cantina`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`customer` (
  `CustomerID` INT(11) NOT NULL AUTO_INCREMENT,
  `CustomerName` VARCHAR(255) NULL DEFAULT NULL,
  `OrdersCompleted` INT(11) NULL DEFAULT '0',
  `orderqueue_OrderID` INT(11) NOT NULL,
  PRIMARY KEY (`CustomerID`, `orderqueue_OrderID`),
  INDEX `CustomerName` (`CustomerName` ASC),
  INDEX `fk_customer_orderqueue1_idx` (`orderqueue_OrderID` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cantina`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`ingredients` (
  `IngredientID` INT(11) NOT NULL AUTO_INCREMENT,
  `IngredientName` VARCHAR(255) NULL DEFAULT NULL,
  `IngredientTotal` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`IngredientID`))
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cantina`.`menuitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`menuitem` (
  `MenuName` VARCHAR(255) NOT NULL,
  `PrimaryIngredient` VARCHAR(255) NULL DEFAULT NULL,
  `ExIng1` VARCHAR(255) NULL DEFAULT NULL,
  `ExIng2` VARCHAR(255) NULL DEFAULT NULL,
  `ExIng3` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`MenuName`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cantina`.`prices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cantina`.`prices` (
  `MenuID` INT(11) NOT NULL AUTO_INCREMENT,
  `MenuName` VARCHAR(255) NULL DEFAULT NULL,
  `MenuPrice` DECIMAL(19,4) NULL DEFAULT '0.0000',
  `menuitem_MenuName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`MenuID`),
  INDEX `fk_prices_menuitem_idx` (`menuitem_MenuName` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
